### ISSUE TITLE
Just some thoughts

### ISSUE THREAD

**Issue by Goeny** [Real-Gecko/Filemin#4]
I am sorry if i annoy you with all these "issues". I am just kinda excited about a new filemanager (something almost every virtualmin user is waiting for, for years).

I have just some thoughts on how i think your filemanager would be even better.
- An address bar to type in a path to go there directly. (i.e: type: /usr/share/webmin/filemin <enter> will get you there immediatly)
- Recursive search. The searchbar in the table now only searches in the current folder. Would be nice to make it search all folders and subfolders under the active folder.
- chmod / chown combination. Opens up a modal where you can set the owner/group and permissions at once. Also an option to use these settings recursive if wanted.
- The action button for select all could be removed since there is a checkbox in the table-header.
- The action button for invert selection only appears (or becomes active) when a selection is made.
- When selecting a folder, give the option to download the complete folder (compressing it before download) This saves some clicks (zipping it, downloading zipped file, removing zipped file again)

Again, I hope i don't offend you with all my jabbering.
If i could i would contribute with some coding. But my knowledge is kinda zero when it comes to perl.
I do have some CSS / HTML / PHP knowledge, so if i could contribute with that in any way, just let me know.

**Comment by Real-Gecko** [comment]
Webmin' file manager is pretty good, but is written in Java and so it is slow and require additional software on user side. That's why I decided to create Filemin.
Actually first version of Filemin was written more than year and half ago. It had all the functions it has now, but it was my first attempt with Perl, so the code was awfull, whole logic was written in one single (OMG) `index.cgi`, and also no Webmin API functions were used at all. So it was buggy and unmaintainable, that's why it was not released to public.
Release of Authentic raised Webmin to new heights, now in it is da best web panel out there :)
That's why approximately three weeks ago I decided to rewrite the module, I switched to Webmin API and separated logic, it reduced bugginess and increased maintainability.
And I`m glad that people interested in this module. IMHO bug fixes, especially those concerning security are the most important now.
However of course all your suggestions are welcomed and I will look into implementing 'em :)

**Comment by lisandi** [comment]
First of all it is a great and VERY welcome stuff you have created here. Some thoughts thow:
1. It should work also on mobiles - responsiveness is quite important when you need to do smaller maintenance work from anywhere i.e. also over 3G with you mobile phone. The filemin tables would be great if they would resize in a responsive way.
2. Creating Symlinks was always very useful in the filemanager - where can I do this in filemin?
especially the possibility to change the destination of a symlink with editing inside the [info] popup in the old filemanager

**Comment by UTCWebDev** [comment]
re: responsive tables, you may find FooTable helpful. It does responsive tables with jQuery + Bootstrap.

**Comment by RWAP** [comment]
I would also ask that the sort options work across several pages - for example it is hard to find the latest files uploaded to an upload folder (which could contain 100 pages)....

I would also ask that the chmod settings (and users) for a file (or group of files) shows the existing settings as this makes it easier to update existing settings
