### ISSUE TITLE
First path breadcrumb for root directory should be / not ~

### ISSUE THREAD

**Issue by swelljoe** [Real-Gecko/Filemin#5]
Hey, amazing work on this project! It already looks really great and does a number of things the current File Manager can do! So exciting. I was just researching JavaScript/HTML5 file managers to try to find one to replace our current file manager...and not having a lot of luck finding one that would fit comfortably into Webmin without a lot of work.

Anyway, in the path breadcrumbs at the top of left of the page, the "root" directory is indicated by "~" which is confusing, as that usually indicates $HOME (i.e. "my user home directory"). If the module supports users and putting them into their own home directory to start with (I don't know, as I haven't tinkered with it enough yet), I could see that being the right symbol for that situation. But, for root user, it makes sense to show it as "/".

**Comment by Real-Gecko** [comment]
Yep, users are locked in their home. This was true for root too and behavior changed only two days ago. I'm thinking about the symbol to replace `~` with, because `/` is not as easy to see and click(that was tested) :)
Maybe something like 'filesystem' or 'root' will do?

**Comment by iliaross** [comment]
I would propose to have something like this for root user

`[root //usr/lib]#`

and something like the following for the regular user:

`[user1 ~/.root/tmp]$`

That would go fine with terminal style and be less confusing!

Sasha, amazing work you are doing!! :)

**Comment by Real-Gecko** [comment]
Replaced `~` for `/` with FontAwesome's HDD icon in version 0.9.
Still open for discussion.

**Comment by iliaross** [comment]
Nice. Please make action icons smaller and `B` is not a good icon for rename. Try fa-terminal, maybe.. I would also keep first to icons with text, like I sent you, `Select All` and `Invert Selection` - that looks cooler, imho. Disk looks good. Move slash further on the right to make it look better.

On the rest -very good job. When I release new version my theme I will try to stress-test your file-manager

Just added a workaround not to show a loader when downloading a file.

**Comment by iliaross** [comment]
- 1. make AJAX call for renaming a file in inline mode.
  1. Move actions fully on the right side of the table and add a bit more there with smaller icons. For critical actions, like delete, confirmation should be added. Like if you click to delete a file, the button will get red after you click it the first time and then if you don't click it again within 3 seconds it will get regular again (i will have this in Theme Restore Default Options on the bext release)
- Make action bar icons appear only when you hover on the row (file). 
1. Probably adding a context menu instead of an action bar would be MUCH better idea as you can add the as many options as you want!

http://medialize.github.io/jQuery-contextMenu/demo.html

**Comment by Real-Gecko** [comment]
I was thinking about adding context menu, to files and folders and removing "Actions" column completely. As I think it will be better to make it in BS popover triggered by hover on file/folder link.
