### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#86]
While Filemin is a part of Webmin now, so why Webmin doesn't autom. update it? I have installed 0.9.6 version, but the latest is 0.9.7. 

Shall I update it manually, or wait for automatic update? How long?

**Comment by jcameron** [comment]
We pick up the latest version of Filemin that exists in it's Github repo at the time each new version of Webmin is built. However, this will almost certainly lag behind the very latest Filemin release.

**Comment by Real-Gecko** [comment]
Latest changes I made 2 days ago are not yet tagged and so are not officially released. I've packed changes to version 0.9.7 for @qooob to check Authentic compatibility. When everything will be ok I'll make release. I haven't been working on Filemin since november so you did not miss much :)

**Comment by iliaross** [comment]
It'll take time to make things work in Authentic. We'll sync to make sure new Webmin release ships latest and working Authentic/Filemin.

**Comment by sz00gun** [comment]
Right,

I tried to install manually:  filemin-0.9.7.linux.wbm.gz  
and filemin doesn't work at all now for me. After installation, there is a blue circle going round and round all the time. 

Where can I find an old file:  filemin-0.9.6.linux.wbm.gz ?? the link on github is dead 404.

Please advise

**Comment by Zen4All** [comment]
You can find all versions here https://github.com/Real-Gecko/filemin/releases

**Comment by sz00gun** [comment]
Thanks Zen, however just noticed Filemin 0.9.7 working fine with old Virtualmin theme, so perhaps there is an issue with Authentic Theme.

Cache removing didn't help. I try to find the problem...

**Comment by sz00gun** [comment]
Try to install 0.10.1 and there is an error.

Downloading https://github.com/Real-Gecko/filemin/archive/v0.10.1.tar.gz ..
Downloading https://codeload.github.com/Real-Gecko/filemin/tar.gz/v0.10.1 ..
.. download complete.
Failed to install module from https://github.com/Real-Gecko/filemin/archive/v0.10.1.tar.gz : Module filemin-0.10.1 requires module libraries

What kind of libraries do I need?

**Comment by iliaross** [comment]
No issue with Authentic Theme. We discussed it with Alexandr. Filemin must make sure not to create conflicts with _already supported_ enrolled codes/features.

It's very complicated to make _proper UI_ and I will not be able to support drastic Filemin's code change for no practical reason. It's easier to fork current version and make it work properly and support all needed/requested features, rather than delivering such support ( stripping down applied module's UI).

I'm not willing to create a fork though and I hope Alexandr will continue the taken course in the past and enroll new features for the users without doing UI stuff (which is not module's business really).

New 17.50 brings support for context menu in Filemin (the 0.9.6 version that is bundled with latest Webmin).

**Comment by Real-Gecko** [comment]
Do not use version 0.10.*! It was a failure :D
0.9.7 is not yet officially released so do not use it too.
Stick with 0.9.6 for now.
New version of Filemin is now WIP, gona be something completely new :D

**Comment by Real-Gecko** [comment]
Added in 1.1.0
