### ISSUE TITLE
Filemin 1.0.0 and Authentic Theme

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#89]
Sasha, hi! Thanks for the new version.

I took a look at the changes you made. I liked new uploads, bookmark manager (has to be done like this since the beginning.), right click context menu and probably the idea of tabbing, when you open an editor window.

However, there are  things I didn't like much:
  **1.** At the moment you open Filemin in completely new window. It should only be done if user wants this.
  **2.** Branding that stands out from _default_ **Webmin** style - not good at all. _Filemin_ is a module and it's very annoying when it looks very different.
  **3.** Editor windows and _Filemin_ table heights are way to small!

---

  **4.** It breaks all of _Authentic Theme_ presently supported features (which I spend around **100 hours** of implementing). _Authentic Theme_ at the moment provides almost all features that new _Filemin_ provides. It misses changing path manually (will be done very soon for the current version). On the other hand current UI for _Filemin_ that is implemented in my theme, in my opinion, is more _fine_. Authentic Theme has keyboard controls, hotkeys and other logic done thoroughly thoughtful - like selecting unselected row on right click and not selecting it, if there are few rows already selected (and click is done inside of selection (just like GMail)), not letting the user to call, for example, Create New Folder, while in editor window, :) and many-many-many other little things that make UI feel great. 
It was implement _long_ time before you decided to push such changes and I would like to ask you for a favor!? Could you _please_ make sure that all of your new features (that are already supported in Authentic Theme) _don not_ break already existing code? 

We **all** would need such features as - a). New uploads; b). symlinks support; c) SELinux support  - that all is pretty much missing the moment. 

Maybe you could support two versions like <1 and >1? That would make more sense? By adding a, b and c new features as well to, let's say 0.9.6.1.

Anyway, what are your thoughts?

**Comment by Real-Gecko** [comment]
1. That was done for reason, now module is theme independent and I can improve it freely.
2. Filemin is non standard Webmin module so it is ok if it looks differently, sytle can be changed at any time. Most important is usability.
3. I'll make height adjustible in time, for now it fits pretty nice inside my laptops screen.
4. I told you not to mix up module functionality with theme functionality as this unwise approach is error prone and leads to unmaintainable code. You did not listen.
   There are different use cases and there are dozens of themes for Webmin, some of them look good, some not, but each one of them represent it's creators' labor. The fact you theme is now default in Virtualmin does not mean that all other themes became obsolete and their developers must be forgotten. Respect other peoples' work. Your theme looks good and it is a part of Webmin, but not the Webmin itself. So instead of trying to put everything inside one theme, try to improve Webmin in major.
   AFAIK right click menu was implemented by you after I released Filemin version 0.10 that already had rightlcik that refused to work only in your theme, so let's not speak about who was first.
   If you tested new version well you would notice that there're already symlinks support, new upload functionality etc.
   If you want to help - you're in contributors list and welcomed to improve the code. Open source is about collaboration and not about being selfish.

**Comment by iliaross** [comment]
Sasha, you say that I didn't listen? Well, it's only true and applies to the right-click-menu - I truly didn't listen about right-click-menu (as before the last release it had been almost 6 months, and I didn't want users to wait any longer) and finished it myself in Authentic Theme, what I planned long time ago.. but it's absolutely not true about the rest of the UI.

Before that, 6 months ago, I made _Filemin_ rock and brought usability to the new level in my theme, while there was not a single hint about contemporary UI in your great file manager, I did all proper UI  functionality/usability. I do respect other people's work but I am being objective here - your new release is a step back for Authentic Theme users. It has only drawbacks. ..and you saying that there are dozens of other themes - is a bluff.

In the end, we are the part of the much bigger project and I bet it's not _us_ alone fully to decide whether forcing a user to open new tab for Filemin or branding it heavily is a right thing to do. In general, in my opinion - it's a bad tone for the users. People use it everyday and they don't want to see any kind of annoying advertising.

You are welcome to continue your module development in any direction you wish, I'm no one is here to tell you what to do. The good part of the open-source projects, that they can be easily forked. Meanwhile, I tend to continue development from where version 0.9.6 was before by adding all requested features by the users and bringing best UI possible.

We're putting everyone here in slightly complicated situation, I think. (I surely didn't do it intentionally and I hope it wasn't your plan either). After all, I believe that in the end, what will really matter - is the opinion of the end users in general, and they are going to decide, what kind of UI/development-pace they enjoy more.

In the end I will do what is best for Webmin/Virtualmin project. If they agree to drop all of my code and replace it with the default one, with Filemin being opened in default tab and your branding - no problem. I will step back. If the team and most importantly the users vote for my implementations, I will fork it and make things shine my own way in Authentic Theme and leave basic support for other themes as it is at the moment (where themes' developers are going to decide how to make the module (Filemin) look like)

Regards,
Ilia

**Comment by Real-Gecko** [comment]
Check [this](http://theme.winfuture.it/) and [this](https://encrypted.google.com/search?q=webmin+themes), be surprised.

**Comment by iliaross** [comment]
I know about the first. The last link gives no precious themes to look at as well. _Sorry_. There are no dozens of themes, like you said. There are no themes yet, that could be compared even remotely.

**Comment by Real-Gecko** [comment]
Корону поправь, жмет а то уже поди :D

**Comment by iliaross** [comment]
.. Sasha, it's mean.

**Comment by swelljoe** [comment]
Y'all be nice. We all need both of you.

I would hope we can sort all these differences out in a way where all of these tools can move forward together.

Some notes that might help provide clarity about the future:
1. Webmin 2.0 will break all old themes (including Authentic and the Virtualmin Framed Theme). Only Authentic will be ported forward. In a few months, there will only be one official theme in Webmin (for a short time) and it will be Authentic. Theming and ui development will be easier, so we hope/expect themes to become more common.
2. Many of Ilia's ui-lib changes will become the standard functions in Webmin's ui-lib. We'll help port Filemin to make use of those new functions when they arrive, if you'd like assistance with it.
3. Bootstrap grid is how we'll be handling layout in the future, but it will be by way of ui-lib changes and not via directly hitting the HTML (though sometimes hitting HTML directly is the quickest path to get there in the beginning, the goal is to allow uniformity, both visual and on the backend for developers).
   4 jQuery will stick around, but we will also likely look into React-baed frontends or some other modern framework for building modern HTML5/JavaScript UIs (though Filemin already now does most of what one would need an AJAX-y UI for).
4. Filemin has been merged into Webmin. Hopefully, we can work together to prevent having to fork it to keep it acting like a Webmin module (opening a new page won't work).

So, going forward Authentic is _the_ theme to target. There will be others (I'll finally finish my Bootstrap theme, probably), but, if you want to target the future UI of Webmin, target Authentic. Ilia is flexible (if ornery at times), and will generally be willing to work with you on making Authentic work together with Filemin. But, he raises some valid points (as do you). Filemin has the potential to be the best web-based file manager available...it's already in the upper echelon of tools in this category. Amazing work in such a short time. Let's keep working together!

In other news, I'm setting up a Mattermost chat server this week, so we can have sort of ongoing team meetings. I'd like to get both of you into that, so we're all able to stay on the same page about the future of things.

Of course, we can't tell you what to do! We're not going to try to tell you how to develop Filemin going forward. We love what you've done and want to see it constantly improving and seeing more and more widespread usage. Hopefully, it can improve in directions that allow us to keep merging it into Webmin core, and allow Ilia's theme to keep working nicely with it.

I agree that many of these functions should be at a lower level than the theme. But, they probably shouldn't be in the module, either; and I guess that's where the webmin-libraries idea came from? That's probably a valid approach, but I think we'd like to see things like AJAX functions and stuff pushed down into core Webmin ui-lib. So, maybe point us in the right direction on how those ought to be implemented and perhaps we can merge them into 2.0, so they don't have to be distributed with the theme _or_ the module.

**Comment by iliaross** [comment]
Joe, thank you for clarifying this up. I'll continue to keep it up.

**Comment by Real-Gecko** [comment]
AFAIK Libraries module idea was not approved upstream and after thinking a little I understood that in current version of Webmin it is completely useless except for Filemin so I denied the idea. As a result you see Filemin 1.0.0, that uses Webmin core in every aspect except GUI.
- I don't want to hear that my module sucks because it's Authentic independent. It's illogical.
- I don't want my changes in Filemin to be overriden on theme side without discussing it with me, that happened more than once.
- I want to have things I add to Filemin work everywhere not only in one theme.

You don't like it - you don't use it, that's the deal.
I'm here not to gather stars or provide some PR campaign.
Me and my customers were the only Filemin users for 1.5 year.
It's release to the public was my 'Thank you' to all The People contributing to Webmin/Virtualmin/Cloudmin.
Discussion is over.
